### ISSUE TITLE
Array.forEach (native) is not a function

### ISSUE THREAD

**Issue by DanPen** [ryaninvents/julia-bridge#3]
Vanilla JS:

```
var JuliaProcess = require('julia-bridge');
var julia = new JuliaProcess();
```

yields error:

```
/Users/Dan/Desktop/julia-bridge-test/node_modules/julia-bridge/src/coffee/JuliaProcess.coffee:37
      return _this[method] = _this.emitter[method].bind(_this.emitter);
                                                   ^
TypeError: undefined is not a function
  at /Users/Dan/Desktop/julia-bridge-test/node_modules/julia-bridge/src/coffee/JuliaProcess.coffee:29:36
  at Array.forEach (native)
  at JuliaProcess (/Users/Dan/Desktop/julia-bridge-test/node_modules/julia-bridge/src/coffee/JuliaProcess.coffee:27:28)
  at Object.<anonymous> (/Users/Dan/Desktop/julia-bridge-test/test.js:1:105)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

Node v0.12.2

**Comment by DanPen** [comment]
It gives the same error with CoffeeScript.   

```
JuliaProcess = require 'julia-bridge'
julia = new JuliaProcess
```

yields:

```
TypeError: undefined is not a function
  at /Users/Dan/Desktop/julia-bridge-test/node_modules/julia-bridge/src/coffee/JuliaProcess.coffee:29:36
  at Array.forEach (native)
  at new JuliaProcess (/Users/Dan/Desktop/julia-bridge-test/node_modules/julia-bridge/src/coffee/JuliaProcess.coffee:27:28)
  at Object.<anonymous> (/Users/Dan/Desktop/julia-bridge-test/test.coffee:2:9)
  at Object.<anonymous> (/Users/Dan/Desktop/julia-bridge-test/test.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:131:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by DanPen** [comment]
I would attempt to fix this, but I have zero experience with CoffeeScript.
